name: teamcore
version: '${project.version}'
main: org.codecraft.teamcore.Teamcore
api-version: 1.20
commands:
  startgame:
    description: Start a teamcore game
    usage: /startgame <world name> <entity names...>
    permission: teamcore.startgame
  endgame:
    description: End a teamcore game prematurely
    usage: /endgame <worldName>
    permission: teamcore.endgame
  movetogame:
    description: Teleports a player to a world
    usage: /movetogame <world> <player>
    permission: teamcore.movetogame
  listgames:
    description: Lists all games/worlds
    usage: /listgames
    permission: teamcore.listworlds
  currentworld:
    description: Get the current world
    usage: /currentworld
    permission: teamcore.currentworld
